### ISSUE TITLE
Error with phone number when seeding data from csv

### ISSUE THREAD

**Issue by yeevon** [yeevon/Kon10DR#6]
Undefined array key "phone"

  at database/seeders/DatabaseSeeder.php:67
     63▕               'email' => $columns[1],
     64▕               'first_name' => $columns[10],
     65▕               'last_name' => $columns[11],
     66▕               'dob' => $formattedDate ,
  ➜  67▕               'phone_no' => $columns['phone'],
     68▕               'country' => $columns[15]
     69▕             ]);
     70▕           }
     71▕           else {

  1   database/seeders/DatabaseSeeder.php:67
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key "phone"", "/var/www/html/database/seeders/DatabaseSeeder.php")
      +22 vendor frames 

  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by elminson** [comment]
This is been fixed in origin/jochi_userDB_Schema_v1 branch and is already in beta
